name: Playwright Tests

on:
  workflow_dispatch:  # Solo permite ejecución manual desde la interfaz de GitHub

jobs:
  test:
    name: 'Ejecutar caso de prueba: ${{ matrix.testcase }}'
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.52.0-jammy
    
    strategy:
      fail-fast: false  # No detener todos los trabajos si uno falla
      matrix:
        testcase: ['CP1', 'CP2', 'CP3', 'CP4', 'CP5', 'CP6']
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Ejecutar test ${{ matrix.testcase }} en modo headless
        run: npx playwright test tests/ejercicio_practico.spec.ts -g "${{ matrix.testcase }}"