name: Playwright Tests

on:
  workflow_dispatch:  # Solo permite ejecución manual desde la interfaz de GitHub

jobs:
  test:
    name: 'CP${{ matrix.testcase }} en ${{ matrix.browser }}'
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.52.0-jammy
      options: --user 1001  # Soluciona problemas de permisos para ejecutar navegadores
    
    strategy:
      fail-fast: false  # No detener todos los trabajos si uno falla
      matrix:
        # Definir la matriz con combinaciones de casos de prueba y navegadores
        include:
          - testcase: '1'
            browser: 'webkit'
          - testcase: '2'
            browser: 'firefox'
          - testcase: '3'
            browser: 'chromium'
          - testcase: '4'
            browser: 'webkit'
          - testcase: '5'
            browser: 'firefox'
          - testcase: '6'
            browser: 'chromium'
    
    steps:
      - uses: actions/checkout@v4
      
      # Necesitamos instalar las dependencias locales del proyecto
      - name: Install dependencies
        run: npm ci
      
      # Asegurar que las dependencias están correctamente instaladas
      - name: Verify Playwright installation
        run: npx playwright --version
      
      - name: Ejecutar test CP${{ matrix.testcase }} en navegador ${{ matrix.browser }}
        run: npx playwright test tests/ejercicio_practico.spec.ts -g "CP${{ matrix.testcase }}" --project=${{ matrix.browser }}
      
      # Guardar reporte HTML
      - name: Guardar reporte HTML
        # Ejecutar este paso incluso si los test fallan
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report-CP${{ matrix.testcase }}-${{ matrix.browser }}
          path: playwright-report/
          retention-days: 30